# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stic_diet.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from New_menu import *

class Ui_MainWindow(object):
    def ouvir_new_menu(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Nouveau_Menu()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 581)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../vector-illustration-de-bande-dessinee-d-39-un-ensemble-traditionnel-de-repas-fast-food_1441-331.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 222, 57);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(350, 0, 331, 431))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../attiéké-sauce-tomate-oignon-2.jpg"))
        self.Image.setObjectName("Image")
        self.bienvenue = QtWidgets.QLabel(self.centralwidget)
        self.bienvenue.setGeometry(QtCore.QRect(50, 220, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.bienvenue.setFont(font)
        self.bienvenue.setObjectName("bienvenue")
        self.AppName = QtWidgets.QLabel(self.centralwidget)
        self.AppName.setGeometry(QtCore.QRect(50, 200, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Raleway Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AppName.setFont(font)
        self.AppName.setObjectName("AppName")
        self.stic = QtWidgets.QLabel(self.centralwidget)
        self.stic.setGeometry(QtCore.QRect(460, 470, 121, 20))
        self.stic.setObjectName("stic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionA_propos = QtWidgets.QAction(MainWindow)
        self.actionA_propos.setObjectName("actionA_propos")
        self.actionNouveau_Menu = QtWidgets.QAction(MainWindow)
        self.actionNouveau_Menu.clicked.connect(self.ouvir_new_menu)
        self.actionNouveau_Menu.setObjectName("actionNouveau_Menu")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionEnregistrer = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionBilan = QtWidgets.QAction(MainWindow)
        self.actionBilan.setObjectName("actionBilan")
        self.actionCalcul_de_l_IMC = QtWidgets.QAction(MainWindow)
        self.actionCalcul_de_l_IMC.setObjectName("actionCalcul_de_l_IMC")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionNouveau_Menu)
        self.menuFichier.addAction(self.actionRecent)
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionBilan)
        self.menuFichier.addAction(self.actionCalcul_de_l_IMC)
        self.menuFichier.addAction(self.actionQuitter)
        self.menuAide.addAction(self.actionA_propos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STIC_Diet"))
        self.bienvenue.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">       STIC DIET</span></p></body></html>"))
        self.AppName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">BIENVENUE DANS</span></p></body></html>"))
        self.stic.setText(_translate("MainWindow", "copyright (c) STIC 2018"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionA_propos.setText(_translate("MainWindow", "A propos...."))
        self.actionNouveau_Menu.setText(_translate("MainWindow", "Nouveau Menu"))
        self.actionNouveau_Menu.setIconText(_translate("MainWindow", "Nouveau Menu"))
        self.actionRecent.setText(_translate("MainWindow", "Recent"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir..."))
        self.actionEnregistrer.setText(_translate("MainWindow", "Enregistrer"))
        self.actionBilan.setText(_translate("MainWindow", "Bilan"))
        self.actionCalcul_de_l_IMC.setText(_translate("MainWindow", "Calcul de l\'IMC"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionQuitter.setShortcut(_translate("MainWindow", "Alt+Q"))
     

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

